### PR TITLE
Read results - bar and node

### LINKED ISSUE #44: SAP2000_Toolkit: Implement Read Results
#### Description:

Read results for global, local, etc.

### LINKED ISSUE #85: SAP2000_Toolkit: Remove Common_Engine reference
#### Broken rules:
All Spatial methods have been moved out of the Common_Engine and deprecated.
See https://github.com/BHoM/BHoM_Engine/issues/1624

#### Suggestions to restore compliance:
The Toolkit should switch to using Spatial_Engine instead.

And unless it's using a non-deprecated method from Common_Engine, the reference should be removed as well.

### PR DESCRIPTION
**Pull request by maryannewachter**
### Issues addressed by this PR
Resolves #44 
Resolves #85 

### Test files
https://github.com/maryannewachter/BHoM_gh/tree/master/SAP2000_Toolkit/SAP2000_Toolkit-%2344-Results

### Changelog
- Adds result support for Bars
- Adds result support for Nodes
- Removes Common Engine references from SAP2000_Adapter
- Removes Common Engine references from SAP2000_Engine

### CODE REVIEW

File: SAP2000_Adapter/CRUD/Read/Results/BarResults.cs [hunk 1]
```diff
@@ -0,0 +1,322 @@
...
+            CheckAndSetUpCases(request);
+            List<string> barIds = CheckGetBarIds(request);
+
+            switch (request.ResultType)
+            {
+                case BarResultType.BarForce:
+                    return ReadBarForce(barIds, request.Divisions);
+                case BarResultType.BarDisplacement:
+                case BarResultType.BarDeformation:
+                    Engine.Reflection.Compute.RecordError("SAP2000 cannot export localised BarDeformations." +
```
Comment (JosefTaylor) [inline SAP2000_Adapter/CRUD/Read/Results/BarResults.cs:55]: Looks like this switch case statement is falling through from BarDisplacement to show the error message for BarDeformations

File: SAP2000_Adapter/CRUD/Read/Results/BarResults.cs [hunk 2]
```diff
@@ -0,0 +1,322 @@
...
+                                                ActionConfig actionConfig = null)
+        {
+            CheckAndSetUpCases(request);
+            List<string> barIds = CheckGetBarIds(request);
+
+            switch (request.ResultType)
+            {
+                case BarResultType.BarForce:
+                    return ReadBarForce(barIds, request.Divisions);
+                case BarResultType.BarDisplacement:
```
Comment (JosefTaylor) [inline SAP2000_Adapter/CRUD/Read/Results/BarResults.cs:53]:
```suggestion
                case BarResultType.BarDisplacement:
                    return ReadBarDisplacement(barIds, request.Divisions);
```
